/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Question1;
 import javax.swing.*;
public class App {


    public static void main(String[] args) {        
        SwingUtilities.invokeLater(() -> {
          String studentNumber = JOptionPane.showInputDialog("Enter Student Number:");
          String name = JOptionPane.showInputDialog("Enter Name:");
          String surname = JOptionPane.showInputDialog("Enter Surname:");
          String email = JOptionPane.showInputDialog("Enter Email Address:");
          String phoneNumber = JOptionPane.showInputDialog("Enter Phone Number:");
          int mark1 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 1:"));
          int mark2 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 2:"));
          int AssignmentMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Assignment Mark:"));
          int examMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Exam Mark:"));
          
          //Calculate DP status
          boolean dpStatus = ((mark1 + mark2 + AssignmentMark) / 3) >= 40;
          
          //Calculate final mark
          double courseworkAverage = (mark1 + mark2 + AssignmentMark) / 3;
          double finalMark = (courseworkAverage * 0.4) + (examMark * 0.6);          
          
          //Pass or fail
            if(finalMark >= 0 && finalMark <= 46) 
            {
                JOptionPane.showMessageDialog(null,"You have received: " + finalMark + "% You have failed.");
            }
                else if(finalMark >= 47 && finalMark <= 49 )            
            {                       
                JOptionPane.showMessageDialog(null,"You have received: " + finalMark + "% You need support.");
            }
                else if(finalMark >= 50 && finalMark <= 74 )             
            {                       
                JOptionPane.showMessageDialog(null,"You have received: " + finalMark + "% Congratulations you have passed.");
            }
                else              
            {                       
                JOptionPane.showMessageDialog(null,"You have received: " + finalMark + "% Congratulations you have achieved a distinction!");
            }           
            
          //Display results
          String message = "Student Number: " + studentNumber + "\n"
                   + "Name: " + name + " " + surname + "\n"
                   + "Email: " + email + "\n"
                   + "Phone Number: " + phoneNumber + "\n"
                   + "Mark 1: " + mark1 + "\n"
                   + "Mark 2: " + mark2 + "\n"
                   + "Assignment Mark: " + AssignmentMark + "\n"
                   + "DP Status: " + (dpStatus ? "Achieved" : "Not Achieved") + "\n"
                   + "Final Mark: " + finalMark;
            JOptionPane.showMessageDialog(null, message);          
        });  
        }
    } 
